### ISSUE TITLE
lolcat: command not found.

### ISSUE THREAD

**Issue by xhani890** [blackhatethicalhacking/OpenRediWrecked#2]
./OpenRediWrecked.sh: line 2: lolcat: command not found

./OpenRediWrecked.sh: line 13: lolcat: command not found
./OpenRediWrecked.sh: line 15: lolcat: command not found
./OpenRediWrecked.sh: line 17: lolcat: command not found

./OpenRediWrecked.sh: line 19: lolcat: command not found
./OpenRediWrecked.sh: line 22: lolcat: command not found
./OpenRediWrecked.sh: line 29: lolcat: command not found
./OpenRediWrecked.sh: line 30: lolcat: command not found
keep showing this get stucks at line 30
any solutions?

**Comment by blackhatethicalhacking** [comment]
The answer is there:
./OpenRediWrecked.sh: line 30: lolcat: command not found

You did not install the pre-requisites.. first install them `pip install lolcat` is one.

**Comment by xhani890** [comment]
thanks
